openapi: 3.0.0
info:
  title: 'Java rest service'
  version: 1.0.0
servers:
  - url: '/java-rest'
paths:
  /api/{id}:
    get:
      operationId: 'findById'
      tags:
        - 'JavaRest'
      parameters:
        - name: id
          in: path
          required: true
          description: 'id in path'
          example: ''
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: 'okay response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FirstObject'

components:
  schemas:
    FirstObject:
      type: object
      required:
      - title
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        innerObject:
          $ref: '#/components/schemas/SecondObject'
        numbers:
          type: array
          items:
            type: integer
            format: int32
        version:
          type: integer
          format: int64
    SecondObject:
      type: object
      properties:
        id:
          type: string
          format: uuid